# -*- coding: utf-8 -*-
"""practice_1_Alg_Lr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhqZ3dJoOGRk5i6QtFwyw-fHJb4D81fT
"""

'''
1.Importing modules
2. Importing Data
3. Data analysis(cleaning,modifying)
4. Data split(train,test)
5. Trainig the model
6. Evaluate model
'''

import pandas as pd
from sklearn.metrics import mean_squared_error

data = pd.read_csv("/content/train.csv")

data.head()

data.tail()

data.describe()

data.info()

data.isnull()

data.isnull().sum()

from matplotlib import pyplot as plt

# scatter plotting
plt.figure(figsize = (5,5))
plt.scatter(data['Aptitude_Test_Score'],data['CGPA'])
plt.xlabel('Aptitude_Test_Score')
plt.ylabel('CGPA')
plt.show

data.head()

x = data[['CGPA']]     # x----independent values y = m(x1+x2+x3)+c
y = data['Aptitude_Test_Score']  # y----dependent values

x

y

plt.figure(figsize = (5,5))
plt.plot(data['Aptitude_Test_Score'],data['CGPA'])
plt.xlabel('Aptitude_Test_Score')
plt.ylabel('CGPA')
plt.show

plt.figure(figsize=(5,5))
plt.bar(data['Aptitude_Test_Score'],data['CGPA'])
plt.xlabel('Aptitude_Test_Score')
plt.ylabel('CGPA')
plt.show

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

x_train

y_train

print(x_train.shape)
print(x_test.shape)

print(y_train.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression
lr = LinearRegression()

lr

x_test.head()

lr.predict(x_test)

lr.fit(x_train, y_train)

x_test.iloc[10]

y_test.iloc[10]

lr.predict([[10]])

lr.predict([[6.68]])

lr.predict([[9.0]])

# ploting Regression Line
figure = plt.figsize = (5,5)
plt.scatter(data['Aptitude_Test_Score'],data['CGPA'])
plt.plot(x_test,lr.predict(x_test),color = 'red')
plt.ylabel('Aptitude_Test_Score')
plt.xlabel('CGPA')
plt.show()

lr.coef_

lr.score(x_test,y_test)